kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: size
          operator: In
          values:
            - large

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  storageClassName: mongodb-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
    name: "mongo-db"
    namespace: "development"
spec: 
    selector: 
      matchLabels: 
        app: "mongo-db"
    replicas: 1
    strategy: 
      type: "RollingUpdate"
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: "mongo-db"
      spec: 
        containers: 
          - name: "mongo-db"
            image: "mongo"
            imagePullPolicy: "Always"
            env: 
              - name: MONGO_INITDB_ROOT_USERNAME
                value: xxxxjjjjj"
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: xxxx
                
            ports: 
              - 
                containerPort: 27017
                name: "mongodb"
                
            volumeMounts: 
              - name: "mongodb-persistent-storage"
                mountPath: "/data/db"

            resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
                
        volumes: 
          - name: "mongodb-persistent-storage"
            persistentVolumeClaim: 
              claimName: "mongodb-pvc"

---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "mongo-db"
    namespace: "development"
    labels: 
      app: "mongo-db"
  spec: 
    ports: 
      - 
        name: "mongodb"
        port: 27017
        nodePort: 30332
    type: "NodePort"
    selector: 
      app: "mongo-db"